version: "3.9"

services:
    web:
        container_name: web
        build: .
        volumes: 
            - ../:/code
        working_dir: /code
        ports: 
            - "8000:8000"
        command: go run server.go